services:
  db:
    image: bitnami/postgresql:latest
    container_name: brevly_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - './docker:/docker-entrypoint-initdb.d'